rules=['Scissors cuts Paper.',
'Paper covers Rock.',
'Rock crushes Lizard.',
'Lizard poisons Spock',
'Spock zaps Wizard.',
'Wizard stuns Batman.',
'Batman scares Spiderman.',
'Spiderman disarms Glock.',
'Glock breaks Rock.',
'Rock interrupts Wizard.',
'Wizard burns Paper.',
'Paper disproves Spock.',
'Spock befuddles Spiderman.',
'Spiderman defeats Lizard.',
'Lizard confuses Batman (presumably because it looks like Killer Croc).',
'Batman dismantles scissors.',
'Scissors cut Wizard.',
'Wizard transforms Lizard.',
'Lizard eats Paper.',
'Paper jams Glock.',
'Glock kills Batman’s mum.',
'Batman explodes Rock.',
'Rock crushes Scissors.',
'Scissors decapitate Lizard.',
'Lizard is too small for Glock.',
'Glock shoots Spock.',
'Spock vaporizes Rock.',
'Rock knocks out Spiderman.',
'Spiderman rips Paper.',
'Paper delays Batman.',
'Batman hangs Spock.',
'Spock smashes Scissors.',
'Scissors cut Spiderman.',
'Spiderman annoys Wizard.',
'Wizard melts Glock.',
'Glock dents Scissors.']
